version: 1.0.{build}
image: Visual Studio 2017

configuration: Release

before_build:
- cmd: nuget restore src\Cardknox.sln

build:
  verbosity: minimal

artifacts:
  - path: '\src\Cardknox.NET\bin\Release\Cardknox.API.Wrapper*.nupkg'
    name: NuGet

deploy:
  provider: NuGet
  api_key:
    secure: bsuOjvFlRd5YC/icDolLT+5pX2ejr4OujY/brObPlc4xSsMJY9I1Gvi9QFLgzYuh
  skip_symbols: false
  artifact: /Cardknox.*\.nupkg/
  on:
    branch: master
