version: 1.0.{build}
image: Visual Studio 2019

before_build:
 - cmd: nuget restore src\Cardknox.sln
 
build:
  verbosity: minimal

artifacts:
  - path: '\src\Cardknox.NET\bin\Release\Cardknox.API.Wrapper*.nupkg'
    name: NuGet

for:

-
 branches:
   only:
     - master
     
 configuration: Release

 deploy:
   provider: NuGet
   api_key:
     secure: bsuOjvFlRd5YC/icDolLT+5pX2ejr4OujY/brObPlc4xSsMJY9I1Gvi9QFLgzYuh
   skip_symbols: false
   skip_tags: true
   artifact: /Cardknox.*\.nupkg/
   on:
     branch: master

-
 branches:
   only:
     - 5.0
     
 configuration: Release

 deploy:
   provider: NuGet
   api_key:
     secure: bsuOjvFlRd5YC/icDolLT+5pX2ejr4OujY/brObPlc4xSsMJY9I1Gvi9QFLgzYuh
   skip_symbols: false
   skip_tags: true
   artifact: /Cardknox.*\.nupkg/
   on:
     branch: 5.0
