title: Cardknox API Wrapper
author: TheScripters
email: adam@adamh.us
description: > # this means to ignore newlines until "baseurl:"
  API Wrapper for Cardknox Payment Processor written in C#.
  
theme: jekyll-theme-slate
google_analytics: UA-30082562-2
show_downloads: true
